### ISSUE TITLE
Count committers by org (in addition to counting commits)?

### ISSUE THREAD

**Issue by RByers** [ArthurSonzogni/ChromeCommitTracker#9]
One number I sometimes like to check on is "how many unique googlers vs. non-googlers landed at least one patch in the past month/quarter/year". Any chance that would be easy to add? UI just like the commit tracker by organization, just counting unique patch authors instead of commits.

**Comment by ArthurSonzogni** [comment]
One visualisation is already counting unique contributors: https://chrome-commit-tracker.arthursonzogni.com/repositories?repositories=angle,chromeos,chromium,dawn,devtool-frontend,gn,pdfium,perfetto,swiftshader,v8,webrtc&what=contributors&grouping=yearly&display=average&kind=author&percentile=0.7071&individual=300&developers=&min_contributions=0
Unfortunately, it is implemented in the non-per-org visualisation.

Yes, this feels valuable to add to this one.

[Contributors][Patch]. lines:[added][removed]

**Comment by ArthurSonzogni** [comment]
Done 🚀 [See data](https://chrome-commit-tracker.arthursonzogni.com/organizations/commits?repositories=chromium&organizations=all&grouping=quarterly&colors=organizations&kind=both&metric=contributor&chart=bar&dates=2021-06-24,2024-09-15)

![image](https://github.com/user-attachments/assets/b4640fce-bdc0-4a64-9fde-01ca415e73c4)

Getting this set up was a bit trickier than expected, but I also managed to refactor some parts of the codebase along the way. This should lead to some nice performance improvements in the tool itself!


**See unique contributor for each quarters:**
 **Date**                        | **2023Q4** | **2024Q1** | **2024Q2** | **2024Q3** 
---------------------------------|------------|------------|------------|------------
 **Individuals**                 | 47         | 49         | 41         | 31         
 **Yandex**                      | 4          | 3          | 5          | 2          
 **Samsung**                     | 32         | 10         | 12         | 8          
 **Google**                      | 1546       | 1552       | 1532       | 1454       
 **Unknown**                     | 22         | 17         | 20         | 21         
 **Igalia**                      | 25         | 26         | 22         | 17         
 **Microsoft**                   | 63         | 88         | 98         | 108        
 **Intel**                       | 35         | 32         | 35         | 32         
 **Meta**                        | 1          | 1          | 4          | 2          
 **ARM**                         | 3          | 2          | 4          | 4          
 **Collabora**                   | 0          | 1          | 1          | 1          
 **Amazon**                      | 1          | 0          | 2          | 1          
 **Nvidia**                      | 0          | 0          | 2          | 1          
 **Brave**                       | 3          | 2          | 2          | 2          
 **Opera**                       | 5          | 3          | 4          | 3          
 **LGE**                         | 3          | 2          | 7          | 9          
 **Canonical**                   | 0          | 0          | 1          | 1          
 **IBM**                         | 1          | 0          | 0          | 1          
 **ByteDance**                   | 3          | 3          | 4          | 5          
 **Naver**                       | 2          | 1          | 2          | 4          
 **Loongson**                    | 2          | 0          | 1          | 1          
 **AMD**                         | 0          | 0          | 0          | 1          
 **University of Illinois**      | 0          | 0          | 1          | 1          
 **Tencent**                     | 2          | 2          | 1          | 0          
 **MediaTek**                    | 0          | 1          | 0          | 0          
 **Dolby**                       | 1          | 1          | 1          | 0          
 **Alibaba**                     | 0          | 1          | 0          | 0          
 **Szeged**                      | 1          | 0          | 0          | 0          
 **Hyperconnect**                | 1          | 0          | 0          | 0          
 **Chinese Academy of Sciences** | 1          | 0          | 0          | 0          
 **Vivaldi**                     | 0          | 0          | 1          | 0
